name: CMake

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  BUILD_TYPE: Release
  CPUNUM: $(cat /proc/cpuinfo | grep processor|wc -l)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: prepare
        run:
          cpu=$(cat /proc/cpuinfo | grep processor|wc -l) &&
          echo "processor num is ${cpu}"  &&
          cmake -B target -Dtest=ON
      - name: test
        working-directory: target
        run: make -j${cpu} && make test
